apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'job']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 5m
      receiver: slack-webhook
      routes:
      - receiver: "null"
        matchers:
        - alertname = "Watchdog"
      - receiver: "null"
        matchers:
        - alertname =~ "KubeCPUOvercommit|KubeMemoryOvercommit|KubeletDown|KubeProxyDown|TargetDown"

    receivers:
    - name: "null"
    - name: slack-webhook
      webhook_configs:
      - url: "http://slack-bot.default.svc.cluster.local:3000/alert"
        send_resolved: true
