apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-bot
  labels:
    app: slack-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-bot
  template:
    metadata:
      labels:
        app: slack-bot
    spec:
      serviceAccountName: slack-bot-ksa
      containers:
      - name: slack-bot
        image: us-central1-docker.pkg.dev/slack-bot-500920/slack-health/slack-bot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: slack-bot-secrets
        env:
        - name: MCP_SERVER_URL
          value: "http://mcp-service:8000/sse"
        - name: SERVICE_NAME
          value: "HotROD"
---
apiVersion: v1
kind: Service
metadata:
  name: slack-bot
spec:
  type: LoadBalancer
  selector:
    app: slack-bot
  ports:
  - port: 3000
    targetPort: 3000
