apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: slack-bot-secrets
  namespace: default
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/slack-bot-500920/secrets/SLACK_BOT_TOKEN/versions/latest"
        fileName: "SLACK_BOT_TOKEN"
      - resourceName: "projects/slack-bot-500920/secrets/SLACK_SIGNING_SECRET/versions/latest"
        fileName: "SLACK_SIGNING_SECRET"
      - resourceName: "projects/slack-bot-500920/secrets/ANTHROPIC_API_KEY/versions/latest"
        fileName: "ANTHROPIC_API_KEY"
  secretObjects:
  - secretName: slack-bot-secrets
    type: Opaque
    data:
    - objectName: "SLACK_BOT_TOKEN"
      key: SLACK_BOT_TOKEN
    - objectName: "SLACK_SIGNING_SECRET"
      key: SLACK_SIGNING_SECRET
    - objectName: "ANTHROPIC_API_KEY"
      key: ANTHROPIC_API_KEY
