apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hotrod
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - hotrod
  selector:
    matchLabels:
      app: hotrod
  endpoints:
  - port: frontend
    path: /metrics
    interval: 15s
